name: labels

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  actions-labeler:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: チェックアウトする
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Node.js をセットアップする
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: 依存関係をインストールする
        id: install-dependencies
        run: npm ci

      - name: ラベルの設定ファイルを生成する
        id: run-labels-cli
        run: npm run --silent labels:generate

      - name: PRの内容に応じてラベルを付与する
        id: run-actions-labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labels.yml
          sync-labels: true
          pr-number: ${{ github.event.pull_request.number }}

  lgtm:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: チェックアウトする
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Node.js をセットアップする
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: 依存関係をインストールする
        id: install-dependencies
        run: npm ci

      - name: 承認時にLGTMラベルを付与する
        id: run-labels-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: npm run --silent labels:attach:lgtm
